# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-2"
  default_tags {
    tags = {
      "Env": "hom"
"Region": "us-east-2"
"managed_by": "Terraform"

    }
  } 
}
