# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-1"
  default_tags {
    tags = {
      "Env": "dev"
"Region": "us-east-1"
"managed_by": "Terraform"

    }
  } 
}
